# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ITCL_video/movDataZynq/prj_vivado/proj_4HP_2GP/proj_4HP_2GP.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ITCL_video/movDataZynq/prj_vivado/proj_4HP_2GP/proj_4HP_2GP.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/ITCL_video/movDataZynq/prj_vivado/proj_4HP_2GP/proj_4HP_2GP.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ITCL_video/movDataZynq/prj_vivado/proj_4HP_2GP/proj_4HP_2GP.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
