
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xwr_data_direct.h"

/*
* The configuration table for devices
*/

XWr_data_direct_Config XWr_data_direct_ConfigTable[XPAR_XWR_DATA_DIRECT_NUM_INSTANCES] =
{
	{
		XPAR_WR_DATA_DIRECT_1_DEVICE_ID,
		XPAR_WR_DATA_DIRECT_1_S_AXI_AXI_LITE_BASEADDR
	}
};


