-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity wr_data_direct is
generic (
    C_S_AXI_AXI_LITE_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_AXI_LITE_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    strm_in_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    strm_in_TVALID : IN STD_LOGIC;
    strm_in_TREADY : OUT STD_LOGIC;
    strm_in_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    strm_in_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    strm_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    strm_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    strm_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    strm_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_dir_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    s_dir_TVALID : OUT STD_LOGIC;
    s_dir_TREADY : IN STD_LOGIC;
    s_data_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    s_data_TVALID : OUT STD_LOGIC;
    s_data_TREADY : IN STD_LOGIC;
    s_axi_Axi_lite_AWVALID : IN STD_LOGIC;
    s_axi_Axi_lite_AWREADY : OUT STD_LOGIC;
    s_axi_Axi_lite_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_ADDR_WIDTH-1 downto 0);
    s_axi_Axi_lite_WVALID : IN STD_LOGIC;
    s_axi_Axi_lite_WREADY : OUT STD_LOGIC;
    s_axi_Axi_lite_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_DATA_WIDTH-1 downto 0);
    s_axi_Axi_lite_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_DATA_WIDTH/8-1 downto 0);
    s_axi_Axi_lite_ARVALID : IN STD_LOGIC;
    s_axi_Axi_lite_ARREADY : OUT STD_LOGIC;
    s_axi_Axi_lite_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_ADDR_WIDTH-1 downto 0);
    s_axi_Axi_lite_RVALID : OUT STD_LOGIC;
    s_axi_Axi_lite_RREADY : IN STD_LOGIC;
    s_axi_Axi_lite_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_DATA_WIDTH-1 downto 0);
    s_axi_Axi_lite_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_Axi_lite_BVALID : OUT STD_LOGIC;
    s_axi_Axi_lite_BREADY : IN STD_LOGIC;
    s_axi_Axi_lite_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of wr_data_direct is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "wr_data_direct_wr_data_direct,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.250000,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=579,HLS_SYN_LUT=513,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal ap_rst_n_inv : STD_LOGIC;
    signal width_img : STD_LOGIC_VECTOR (31 downto 0);
    signal base_addr : STD_LOGIC_VECTOR (31 downto 0);
    signal statistics_ap_vld : STD_LOGIC;
    signal numWrites : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal tmp_nbreadreq_fu_104_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal tmp_reg_264 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_264_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal tmp_reg_264_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_dir_U_apdone_blk : STD_LOGIC;
    signal regslice_both_s_data_U_apdone_blk : STD_LOGIC;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal strm_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal s_dir_TDATA_blk_n : STD_LOGIC;
    signal s_data_TDATA_blk_n : STD_LOGIC;
    signal base_addr_read_reg_259 : STD_LOGIC_VECTOR (31 downto 0);
    signal base_addr_read_reg_259_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal base_addr_read_reg_259_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal base_addr_read_reg_259_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_264_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_264_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal data_wr_reg_268 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_wr_reg_268_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal data_wr_reg_268_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal data_wr_reg_268_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal col_reg_273 : STD_LOGIC_VECTOR (10 downto 0);
    signal col_reg_273_pp0_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_fu_217_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln66_reg_288 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln66_reg_288_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln66_reg_288_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln66_reg_288_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_251_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln61_reg_298 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal row_fu_189_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal width_fu_175_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln66_fu_211_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_fu_234_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln61_3_fu_241_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_251_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_251_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_251_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_251_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_strm_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal strm_in_TVALID_int_regslice : STD_LOGIC;
    signal strm_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_strm_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_strm_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_strm_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_user_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_strm_in_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_strm_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_id_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_strm_in_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_strm_in_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_dest_V_U_ack_in : STD_LOGIC;
    signal s_dir_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal s_dir_TVALID_int_regslice : STD_LOGIC;
    signal s_dir_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_dir_U_vld_out : STD_LOGIC;
    signal s_data_TVALID_int_regslice : STD_LOGIC;
    signal s_data_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_data_U_vld_out : STD_LOGIC;
    signal grp_fu_251_p00 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_251_p10 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_251_p20 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component wr_data_direct_mac_muladd_12ns_11ns_11ns_22_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component wr_data_direct_Axi_lite_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        width_img : OUT STD_LOGIC_VECTOR (31 downto 0);
        base_addr : OUT STD_LOGIC_VECTOR (31 downto 0);
        statistics : IN STD_LOGIC_VECTOR (31 downto 0);
        statistics_ap_vld : IN STD_LOGIC );
    end component;


    component wr_data_direct_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    Axi_lite_s_axi_U : component wr_data_direct_Axi_lite_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXI_LITE_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXI_LITE_DATA_WIDTH)
    port map (
        AWVALID => s_axi_Axi_lite_AWVALID,
        AWREADY => s_axi_Axi_lite_AWREADY,
        AWADDR => s_axi_Axi_lite_AWADDR,
        WVALID => s_axi_Axi_lite_WVALID,
        WREADY => s_axi_Axi_lite_WREADY,
        WDATA => s_axi_Axi_lite_WDATA,
        WSTRB => s_axi_Axi_lite_WSTRB,
        ARVALID => s_axi_Axi_lite_ARVALID,
        ARREADY => s_axi_Axi_lite_ARREADY,
        ARADDR => s_axi_Axi_lite_ARADDR,
        RVALID => s_axi_Axi_lite_RVALID,
        RREADY => s_axi_Axi_lite_RREADY,
        RDATA => s_axi_Axi_lite_RDATA,
        RRESP => s_axi_Axi_lite_RRESP,
        BVALID => s_axi_Axi_lite_BVALID,
        BREADY => s_axi_Axi_lite_BREADY,
        BRESP => s_axi_Axi_lite_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        width_img => width_img,
        base_addr => base_addr,
        statistics => select_ln66_reg_288_pp0_iter3_reg,
        statistics_ap_vld => statistics_ap_vld);

    mac_muladd_12ns_11ns_11ns_22_4_1_U1 : component wr_data_direct_mac_muladd_12ns_11ns_11ns_22_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 12,
        din1_WIDTH => 11,
        din2_WIDTH => 11,
        dout_WIDTH => 22)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_251_p0,
        din1 => grp_fu_251_p1,
        din2 => grp_fu_251_p2,
        ce => grp_fu_251_ce,
        dout => grp_fu_251_p3);

    regslice_both_strm_in_V_data_V_U : component wr_data_direct_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TDATA,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_data_V_U_ack_in,
        data_out => strm_in_TDATA_int_regslice,
        vld_out => strm_in_TVALID_int_regslice,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_data_V_U_apdone_blk);

    regslice_both_strm_in_V_keep_V_U : component wr_data_direct_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TKEEP,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_keep_V_U_ack_in,
        data_out => strm_in_TKEEP_int_regslice,
        vld_out => regslice_both_strm_in_V_keep_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_keep_V_U_apdone_blk);

    regslice_both_strm_in_V_strb_V_U : component wr_data_direct_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TSTRB,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_strb_V_U_ack_in,
        data_out => strm_in_TSTRB_int_regslice,
        vld_out => regslice_both_strm_in_V_strb_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_strb_V_U_apdone_blk);

    regslice_both_strm_in_V_user_V_U : component wr_data_direct_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TUSER,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_user_V_U_ack_in,
        data_out => strm_in_TUSER_int_regslice,
        vld_out => regslice_both_strm_in_V_user_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_user_V_U_apdone_blk);

    regslice_both_strm_in_V_last_V_U : component wr_data_direct_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TLAST,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_last_V_U_ack_in,
        data_out => strm_in_TLAST_int_regslice,
        vld_out => regslice_both_strm_in_V_last_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_last_V_U_apdone_blk);

    regslice_both_strm_in_V_id_V_U : component wr_data_direct_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TID,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_id_V_U_ack_in,
        data_out => strm_in_TID_int_regslice,
        vld_out => regslice_both_strm_in_V_id_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_id_V_U_apdone_blk);

    regslice_both_strm_in_V_dest_V_U : component wr_data_direct_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TDEST,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_dest_V_U_ack_in,
        data_out => strm_in_TDEST_int_regslice,
        vld_out => regslice_both_strm_in_V_dest_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_dest_V_U_apdone_blk);

    regslice_both_s_dir_U : component wr_data_direct_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_dir_TDATA_int_regslice,
        vld_in => s_dir_TVALID_int_regslice,
        ack_in => s_dir_TREADY_int_regslice,
        data_out => s_dir_TDATA,
        vld_out => regslice_both_s_dir_U_vld_out,
        ack_out => s_dir_TREADY,
        apdone_blk => regslice_both_s_dir_U_apdone_blk);

    regslice_both_s_data_U : component wr_data_direct_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => data_wr_reg_268_pp0_iter3_reg,
        vld_in => s_data_TVALID_int_regslice,
        ack_in => s_data_TREADY_int_regslice,
        data_out => s_data_TDATA,
        vld_out => regslice_both_s_data_U_vld_out,
        ack_out => s_data_TREADY,
        apdone_blk => regslice_both_s_data_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (tmp_reg_264_pp0_iter2_reg = ap_const_lv1_1))) then
                add_ln61_reg_298 <= grp_fu_251_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                base_addr_read_reg_259 <= base_addr;
                base_addr_read_reg_259_pp0_iter1_reg <= base_addr_read_reg_259;
                col_reg_273_pp0_iter1_reg <= col_reg_273;
                data_wr_reg_268_pp0_iter1_reg <= data_wr_reg_268;
                select_ln66_reg_288_pp0_iter1_reg <= select_ln66_reg_288;
                tmp_reg_264 <= tmp_nbreadreq_fu_104_p9;
                tmp_reg_264_pp0_iter1_reg <= tmp_reg_264;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                base_addr_read_reg_259_pp0_iter2_reg <= base_addr_read_reg_259_pp0_iter1_reg;
                base_addr_read_reg_259_pp0_iter3_reg <= base_addr_read_reg_259_pp0_iter2_reg;
                data_wr_reg_268_pp0_iter2_reg <= data_wr_reg_268_pp0_iter1_reg;
                data_wr_reg_268_pp0_iter3_reg <= data_wr_reg_268_pp0_iter2_reg;
                select_ln66_reg_288_pp0_iter2_reg <= select_ln66_reg_288_pp0_iter1_reg;
                select_ln66_reg_288_pp0_iter3_reg <= select_ln66_reg_288_pp0_iter2_reg;
                tmp_reg_264_pp0_iter2_reg <= tmp_reg_264_pp0_iter1_reg;
                tmp_reg_264_pp0_iter3_reg <= tmp_reg_264_pp0_iter2_reg;
                tmp_reg_264_pp0_iter4_reg <= tmp_reg_264_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_104_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                col_reg_273 <= strm_in_TDATA_int_regslice(26 downto 16);
                data_wr_reg_268 <= strm_in_TDATA_int_regslice(63 downto 32);
                select_ln66_reg_288 <= select_ln66_fu_217_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (tmp_nbreadreq_fu_104_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                numWrites <= select_ln66_fu_217_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln66_fu_211_p2 <= std_logic_vector(unsigned(numWrites) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_nbreadreq_fu_104_p9, tmp_reg_264_pp0_iter3_reg, tmp_reg_264_pp0_iter4_reg, regslice_both_s_dir_U_apdone_blk, regslice_both_s_data_U_apdone_blk, ap_enable_reg_pp0_iter5, strm_in_TVALID_int_regslice, s_dir_TREADY_int_regslice, s_data_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_s_data_U_apdone_blk = ap_const_logic_1) or (regslice_both_s_dir_U_apdone_blk = ap_const_logic_1) or ((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_const_logic_1) and (tmp_nbreadreq_fu_104_p9 = ap_const_lv1_1) and (strm_in_TVALID_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_nbreadreq_fu_104_p9, tmp_reg_264_pp0_iter3_reg, ap_block_state5_io, tmp_reg_264_pp0_iter4_reg, regslice_both_s_dir_U_apdone_blk, regslice_both_s_data_U_apdone_blk, ap_block_state6_io, ap_enable_reg_pp0_iter5, strm_in_TVALID_int_regslice, s_dir_TREADY_int_regslice, s_data_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_s_data_U_apdone_blk = ap_const_logic_1) or (regslice_both_s_dir_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state6_io) or ((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_const_logic_1) and (tmp_nbreadreq_fu_104_p9 = ap_const_lv1_1) and (strm_in_TVALID_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_nbreadreq_fu_104_p9, tmp_reg_264_pp0_iter3_reg, ap_block_state5_io, tmp_reg_264_pp0_iter4_reg, regslice_both_s_dir_U_apdone_blk, regslice_both_s_data_U_apdone_blk, ap_block_state6_io, ap_enable_reg_pp0_iter5, strm_in_TVALID_int_regslice, s_dir_TREADY_int_regslice, s_data_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_s_data_U_apdone_blk = ap_const_logic_1) or (regslice_both_s_dir_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state6_io) or ((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_const_logic_1) and (tmp_nbreadreq_fu_104_p9 = ap_const_lv1_1) and (strm_in_TVALID_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(tmp_nbreadreq_fu_104_p9, strm_in_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((tmp_nbreadreq_fu_104_p9 = ap_const_lv1_1) and (strm_in_TVALID_int_regslice = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_io_assign_proc : process(tmp_reg_264_pp0_iter3_reg, s_dir_TREADY_int_regslice, s_data_TREADY_int_regslice)
    begin
                ap_block_state5_io <= (((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(tmp_reg_264_pp0_iter3_reg, s_dir_TREADY_int_regslice, s_data_TREADY_int_regslice)
    begin
                ap_block_state5_pp0_stage0_iter4 <= (((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state6_io_assign_proc : process(tmp_reg_264_pp0_iter4_reg, s_dir_TREADY_int_regslice, s_data_TREADY_int_regslice)
    begin
                ap_block_state6_io <= (((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state6_pp0_stage0_iter5_assign_proc : process(tmp_reg_264_pp0_iter4_reg, regslice_both_s_dir_U_apdone_blk, regslice_both_s_data_U_apdone_blk, s_dir_TREADY_int_regslice, s_data_TREADY_int_regslice)
    begin
                ap_block_state6_pp0_stage0_iter5 <= ((regslice_both_s_data_U_apdone_blk = ap_const_logic_1) or (regslice_both_s_dir_U_apdone_blk = ap_const_logic_1) or ((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_data_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1) and (s_dir_TREADY_int_regslice = ap_const_logic_0)));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    grp_fu_251_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_251_ce <= ap_const_logic_1;
        else 
            grp_fu_251_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_251_p0 <= grp_fu_251_p00(12 - 1 downto 0);
    grp_fu_251_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_fu_175_p1),22));
    grp_fu_251_p1 <= grp_fu_251_p10(11 - 1 downto 0);
    grp_fu_251_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_fu_189_p1),22));
    grp_fu_251_p2 <= grp_fu_251_p20(11 - 1 downto 0);
    grp_fu_251_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_reg_273_pp0_iter1_reg),22));
    row_fu_189_p1 <= strm_in_TDATA_int_regslice(11 - 1 downto 0);

    s_data_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_264_pp0_iter3_reg, tmp_reg_264_pp0_iter4_reg, ap_enable_reg_pp0_iter5, ap_block_pp0_stage0, s_data_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)))) then 
            s_data_TDATA_blk_n <= s_data_TREADY_int_regslice;
        else 
            s_data_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_data_TVALID <= regslice_both_s_data_U_vld_out;

    s_data_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_264_pp0_iter3_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            s_data_TVALID_int_regslice <= ap_const_logic_1;
        else 
            s_data_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    s_dir_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_264_pp0_iter3_reg, tmp_reg_264_pp0_iter4_reg, ap_enable_reg_pp0_iter5, ap_block_pp0_stage0, s_dir_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (tmp_reg_264_pp0_iter4_reg = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)))) then 
            s_dir_TDATA_blk_n <= s_dir_TREADY_int_regslice;
        else 
            s_dir_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_dir_TDATA_int_regslice <= std_logic_vector(unsigned(zext_ln61_3_fu_241_p1) + unsigned(base_addr_read_reg_259_pp0_iter3_reg));
    s_dir_TVALID <= regslice_both_s_dir_U_vld_out;

    s_dir_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_264_pp0_iter3_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            s_dir_TVALID_int_regslice <= ap_const_logic_1;
        else 
            s_dir_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln66_fu_217_p3 <= 
        ap_const_lv32_1 when (strm_in_TUSER_int_regslice(0) = '1') else 
        add_ln66_fu_211_p2;
    shl_ln_fu_234_p3 <= (add_ln61_reg_298 & ap_const_lv2_0);

    statistics_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_264_pp0_iter3_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_264_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            statistics_ap_vld <= ap_const_logic_1;
        else 
            statistics_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    strm_in_TDATA_blk_n_assign_proc : process(tmp_nbreadreq_fu_104_p9, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, strm_in_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (tmp_nbreadreq_fu_104_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            strm_in_TDATA_blk_n <= strm_in_TVALID_int_regslice;
        else 
            strm_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    strm_in_TREADY <= regslice_both_strm_in_V_data_V_U_ack_in;

    strm_in_TREADY_int_regslice_assign_proc : process(tmp_nbreadreq_fu_104_p9, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (tmp_nbreadreq_fu_104_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            strm_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            strm_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_nbreadreq_fu_104_p9 <= (0=>(strm_in_TVALID_int_regslice), others=>'-');
    width_fu_175_p1 <= width_img(12 - 1 downto 0);
    zext_ln61_3_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_234_p3),32));
end behav;
