
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpath_thr_axis.h"

/*
* The configuration table for devices
*/

XPath_thr_axis_Config XPath_thr_axis_ConfigTable[XPAR_XPATH_THR_AXIS_NUM_INSTANCES] =
{
	{
		XPAR_PATH_THR_AXIS_0_DEVICE_ID,
		XPAR_PATH_THR_AXIS_0_S_AXI_AXI_LITE_BASEADDR
	}
};


