
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xwr_data_dir_adv.h"

/*
* The configuration table for devices
*/

XWr_data_dir_adv_Config XWr_data_dir_adv_ConfigTable[XPAR_XWR_DATA_DIR_ADV_NUM_INSTANCES] =
{
	{
		XPAR_WRITE_MODULE_0_WR_DATA_DIR_ADV_0_DEVICE_ID,
		XPAR_WRITE_MODULE_0_WR_DATA_DIR_ADV_0_S_AXI_AXI_LITE_BASEADDR
	},
	{
		XPAR_WRITE_MODULE_1_WR_DATA_DIR_ADV_1_DEVICE_ID,
		XPAR_WRITE_MODULE_1_WR_DATA_DIR_ADV_1_S_AXI_AXI_LITE_BASEADDR
	}
};


