
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xcolector_display.h"

/*
* The configuration table for devices
*/

XColector_display_Config XColector_display_ConfigTable[XPAR_XCOLECTOR_DISPLAY_NUM_INSTANCES] =
{
	{
		XPAR_DISPLAY_0_COLECTOR_DISPLAY_0_DEVICE_ID,
		XPAR_DISPLAY_0_COLECTOR_DISPLAY_0_S_AXI_AXI_LITE_BASEADDR
	},
	{
		XPAR_DISPLAY_1_COLECTOR_DISPLAY_1_DEVICE_ID,
		XPAR_DISPLAY_1_COLECTOR_DISPLAY_1_S_AXI_AXI_LITE_BASEADDR
	}
};


