# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_2_0/design_1_axi_smc_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_2_0 || ORIG_REF_NAME==design_1_axi_smc_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_display0_0/design_1_axi_vdma_display0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_display0_0 || ORIG_REF_NAME==design_1_axi_vdma_display0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_colector_display_0_0/design_1_colector_display_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_colector_display_0_0 || ORIG_REF_NAME==design_1_colector_display_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_3_0/design_1_axi_smc_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_3_0 || ORIG_REF_NAME==design_1_axi_smc_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_display1_0/design_1_axi_vdma_display1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_display1_0 || ORIG_REF_NAME==design_1_axi_vdma_display1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_colector_display_1_0/design_1_colector_display_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_colector_display_1_0 || ORIG_REF_NAME==design_1_colector_display_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_frame_ptrs_0/design_1_frame_ptrs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_frame_ptrs_0 || ORIG_REF_NAME==design_1_frame_ptrs_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_4/design_1_axi_smc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_4 || ORIG_REF_NAME==design_1_axi_smc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_0 || ORIG_REF_NAME==design_1_axi_vdma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1_0/design_1_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1_0 || ORIG_REF_NAME==design_1_axi_smc_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_1_0/design_1_axi_vdma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_1_0 || ORIG_REF_NAME==design_1_axi_vdma_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_bit_0_0/design_1_xlslice_bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_bit_0_0 || ORIG_REF_NAME==design_1_xlslice_bit_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_bit_1_0/design_1_xlslice_bit_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_bit_1_0 || ORIG_REF_NAME==design_1_xlslice_bit_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_bit_2_0/design_1_xlslice_bit_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_bit_2_0 || ORIG_REF_NAME==design_1_xlslice_bit_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_bit_3_0/design_1_xlslice_bit_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_bit_3_0 || ORIG_REF_NAME==design_1_xlslice_bit_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adapter_axi_0_0/design_1_adapter_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adapter_axi_0_0 || ORIG_REF_NAME==design_1_adapter_axi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dir_fifo_0_0/design_1_axis_dir_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_dir_fifo_0_0 || ORIG_REF_NAME==design_1_axis_dir_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_wr_data_dir_adv_0_0/design_1_wr_data_dir_adv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_wr_data_dir_adv_0_0 || ORIG_REF_NAME==design_1_wr_data_dir_adv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adapter_axi_1_0/design_1_adapter_axi_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adapter_axi_1_0 || ORIG_REF_NAME==design_1_adapter_axi_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_0/design_1_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_0 || ORIG_REF_NAME==design_1_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dir_fifo_1_0/design_1_axis_dir_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_dir_fifo_1_0 || ORIG_REF_NAME==design_1_axis_dir_fifo_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_wr_data_dir_adv_1_0/design_1_wr_data_dir_adv_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_wr_data_dir_adv_1_0 || ORIG_REF_NAME==design_1_wr_data_dir_adv_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: d:/ITCL_video/movDataZynq/prj_vivado/proj_4HP_2GP/proj_4HP_2GP.gen/sources_1/bd/design_1/design_1_ooc.xdc
