
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xcpydata_copro.h"

/*
* The configuration table for devices
*/

XCpydata_copro_Config XCpydata_copro_ConfigTable[XPAR_XCPYDATA_COPRO_NUM_INSTANCES] =
{
	{
		XPAR_CPYDATA_COPRO_0_DEVICE_ID,
		XPAR_CPYDATA_COPRO_0_S_AXI_AXI_LITE_BASEADDR,
		XPAR_CPYDATA_COPRO_0_S_AXI_CONTROL_BASEADDR
	}
};


