-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity path_thr_axis is
generic (
    C_S_AXI_AXI_LITE_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_AXI_LITE_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    strm_in_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    strm_in_TVALID : IN STD_LOGIC;
    strm_in_TREADY : OUT STD_LOGIC;
    strm_in_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    strm_in_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    strm_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    strm_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    strm_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    strm_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    strm_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    strm_out_TVALID : OUT STD_LOGIC;
    strm_out_TREADY : IN STD_LOGIC;
    strm_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    strm_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    strm_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    strm_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    strm_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    strm_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_Axi_lite_AWVALID : IN STD_LOGIC;
    s_axi_Axi_lite_AWREADY : OUT STD_LOGIC;
    s_axi_Axi_lite_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_ADDR_WIDTH-1 downto 0);
    s_axi_Axi_lite_WVALID : IN STD_LOGIC;
    s_axi_Axi_lite_WREADY : OUT STD_LOGIC;
    s_axi_Axi_lite_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_DATA_WIDTH-1 downto 0);
    s_axi_Axi_lite_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_DATA_WIDTH/8-1 downto 0);
    s_axi_Axi_lite_ARVALID : IN STD_LOGIC;
    s_axi_Axi_lite_ARREADY : OUT STD_LOGIC;
    s_axi_Axi_lite_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_ADDR_WIDTH-1 downto 0);
    s_axi_Axi_lite_RVALID : OUT STD_LOGIC;
    s_axi_Axi_lite_RREADY : IN STD_LOGIC;
    s_axi_Axi_lite_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXI_LITE_DATA_WIDTH-1 downto 0);
    s_axi_Axi_lite_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_Axi_lite_BVALID : OUT STD_LOGIC;
    s_axi_Axi_lite_BREADY : IN STD_LOGIC;
    s_axi_Axi_lite_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of path_thr_axis is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "path_thr_axis_path_thr_axis,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.838000,HLS_SYN_LAT=106,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=212,HLS_SYN_LUT=330,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_rst_n_inv : STD_LOGIC;
    signal addr : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_start : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_done : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_idle : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_ready : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_in_TREADY : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TREADY : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_statistics : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_statistics_ap_vld : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_flag_0_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_flag_0_out_ap_vld : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_loc_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_loc_0_out_ap_vld : STD_LOGIC;
    signal grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal addr_flag_0_loc_fu_78 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_loc_0_loc_fu_74 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal regslice_both_strm_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal addr_flag_0_loc_load_load_fu_124_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal regslice_both_strm_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal strm_in_TVALID_int_regslice : STD_LOGIC;
    signal strm_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_strm_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_strm_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_strm_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_user_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_strm_in_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_strm_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_id_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_strm_in_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_strm_in_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal strm_in_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_strm_in_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_in_V_dest_V_U_ack_in : STD_LOGIC;
    signal strm_out_TVALID_int_regslice : STD_LOGIC;
    signal strm_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_strm_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_strm_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_strm_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_strm_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_strm_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_out_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_strm_out_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_strm_out_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_strm_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_strm_out_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_out_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_strm_out_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_strm_out_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_strm_out_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_strm_out_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_strm_out_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component path_thr_axis_path_thr_axis_Pipeline_VITIS_LOOP_31_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        addr_load : IN STD_LOGIC_VECTOR (31 downto 0);
        strm_in_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        strm_in_TVALID : IN STD_LOGIC;
        strm_in_TREADY : OUT STD_LOGIC;
        strm_in_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        strm_in_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        strm_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        strm_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        strm_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        strm_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        strm_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        strm_out_TVALID : OUT STD_LOGIC;
        strm_out_TREADY : IN STD_LOGIC;
        strm_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        strm_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        strm_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        strm_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        strm_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        strm_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        statistics : OUT STD_LOGIC_VECTOR (31 downto 0);
        statistics_ap_vld : OUT STD_LOGIC;
        addr_flag_0_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        addr_flag_0_out_ap_vld : OUT STD_LOGIC;
        addr_loc_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        addr_loc_0_out_ap_vld : OUT STD_LOGIC );
    end component;


    component path_thr_axis_Axi_lite_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        statistics : IN STD_LOGIC_VECTOR (31 downto 0);
        statistics_ap_vld : IN STD_LOGIC );
    end component;


    component path_thr_axis_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82 : component path_thr_axis_path_thr_axis_Pipeline_VITIS_LOOP_31_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_start,
        ap_done => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_done,
        ap_idle => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_idle,
        ap_ready => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_ready,
        addr_load => addr,
        strm_in_TDATA => strm_in_TDATA_int_regslice,
        strm_in_TVALID => strm_in_TVALID_int_regslice,
        strm_in_TREADY => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_in_TREADY,
        strm_in_TKEEP => strm_in_TKEEP_int_regslice,
        strm_in_TSTRB => strm_in_TSTRB_int_regslice,
        strm_in_TUSER => strm_in_TUSER_int_regslice,
        strm_in_TLAST => strm_in_TLAST_int_regslice,
        strm_in_TID => strm_in_TID_int_regslice,
        strm_in_TDEST => strm_in_TDEST_int_regslice,
        strm_out_TDATA => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TDATA,
        strm_out_TVALID => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID,
        strm_out_TREADY => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TREADY,
        strm_out_TKEEP => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TKEEP,
        strm_out_TSTRB => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TSTRB,
        strm_out_TUSER => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TUSER,
        strm_out_TLAST => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TLAST,
        strm_out_TID => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TID,
        strm_out_TDEST => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TDEST,
        statistics => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_statistics,
        statistics_ap_vld => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_statistics_ap_vld,
        addr_flag_0_out => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_flag_0_out,
        addr_flag_0_out_ap_vld => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_flag_0_out_ap_vld,
        addr_loc_0_out => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_loc_0_out,
        addr_loc_0_out_ap_vld => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_loc_0_out_ap_vld);

    Axi_lite_s_axi_U : component path_thr_axis_Axi_lite_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXI_LITE_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXI_LITE_DATA_WIDTH)
    port map (
        AWVALID => s_axi_Axi_lite_AWVALID,
        AWREADY => s_axi_Axi_lite_AWREADY,
        AWADDR => s_axi_Axi_lite_AWADDR,
        WVALID => s_axi_Axi_lite_WVALID,
        WREADY => s_axi_Axi_lite_WREADY,
        WDATA => s_axi_Axi_lite_WDATA,
        WSTRB => s_axi_Axi_lite_WSTRB,
        ARVALID => s_axi_Axi_lite_ARVALID,
        ARREADY => s_axi_Axi_lite_ARREADY,
        ARADDR => s_axi_Axi_lite_ARADDR,
        RVALID => s_axi_Axi_lite_RVALID,
        RREADY => s_axi_Axi_lite_RREADY,
        RDATA => s_axi_Axi_lite_RDATA,
        RRESP => s_axi_Axi_lite_RRESP,
        BVALID => s_axi_Axi_lite_BVALID,
        BREADY => s_axi_Axi_lite_BREADY,
        BRESP => s_axi_Axi_lite_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        statistics => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_statistics,
        statistics_ap_vld => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_statistics_ap_vld);

    regslice_both_strm_in_V_data_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TDATA,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_data_V_U_ack_in,
        data_out => strm_in_TDATA_int_regslice,
        vld_out => strm_in_TVALID_int_regslice,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_data_V_U_apdone_blk);

    regslice_both_strm_in_V_keep_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TKEEP,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_keep_V_U_ack_in,
        data_out => strm_in_TKEEP_int_regslice,
        vld_out => regslice_both_strm_in_V_keep_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_keep_V_U_apdone_blk);

    regslice_both_strm_in_V_strb_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TSTRB,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_strb_V_U_ack_in,
        data_out => strm_in_TSTRB_int_regslice,
        vld_out => regslice_both_strm_in_V_strb_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_strb_V_U_apdone_blk);

    regslice_both_strm_in_V_user_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TUSER,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_user_V_U_ack_in,
        data_out => strm_in_TUSER_int_regslice,
        vld_out => regslice_both_strm_in_V_user_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_user_V_U_apdone_blk);

    regslice_both_strm_in_V_last_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TLAST,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_last_V_U_ack_in,
        data_out => strm_in_TLAST_int_regslice,
        vld_out => regslice_both_strm_in_V_last_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_last_V_U_apdone_blk);

    regslice_both_strm_in_V_id_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TID,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_id_V_U_ack_in,
        data_out => strm_in_TID_int_regslice,
        vld_out => regslice_both_strm_in_V_id_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_id_V_U_apdone_blk);

    regslice_both_strm_in_V_dest_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => strm_in_TDEST,
        vld_in => strm_in_TVALID,
        ack_in => regslice_both_strm_in_V_dest_V_U_ack_in,
        data_out => strm_in_TDEST_int_regslice,
        vld_out => regslice_both_strm_in_V_dest_V_U_vld_out,
        ack_out => strm_in_TREADY_int_regslice,
        apdone_blk => regslice_both_strm_in_V_dest_V_U_apdone_blk);

    regslice_both_strm_out_V_data_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TDATA,
        vld_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID,
        ack_in => strm_out_TREADY_int_regslice,
        data_out => strm_out_TDATA,
        vld_out => regslice_both_strm_out_V_data_V_U_vld_out,
        ack_out => strm_out_TREADY,
        apdone_blk => regslice_both_strm_out_V_data_V_U_apdone_blk);

    regslice_both_strm_out_V_keep_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TKEEP,
        vld_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID,
        ack_in => regslice_both_strm_out_V_keep_V_U_ack_in_dummy,
        data_out => strm_out_TKEEP,
        vld_out => regslice_both_strm_out_V_keep_V_U_vld_out,
        ack_out => strm_out_TREADY,
        apdone_blk => regslice_both_strm_out_V_keep_V_U_apdone_blk);

    regslice_both_strm_out_V_strb_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TSTRB,
        vld_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID,
        ack_in => regslice_both_strm_out_V_strb_V_U_ack_in_dummy,
        data_out => strm_out_TSTRB,
        vld_out => regslice_both_strm_out_V_strb_V_U_vld_out,
        ack_out => strm_out_TREADY,
        apdone_blk => regslice_both_strm_out_V_strb_V_U_apdone_blk);

    regslice_both_strm_out_V_user_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TUSER,
        vld_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID,
        ack_in => regslice_both_strm_out_V_user_V_U_ack_in_dummy,
        data_out => strm_out_TUSER,
        vld_out => regslice_both_strm_out_V_user_V_U_vld_out,
        ack_out => strm_out_TREADY,
        apdone_blk => regslice_both_strm_out_V_user_V_U_apdone_blk);

    regslice_both_strm_out_V_last_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TLAST,
        vld_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID,
        ack_in => regslice_both_strm_out_V_last_V_U_ack_in_dummy,
        data_out => strm_out_TLAST,
        vld_out => regslice_both_strm_out_V_last_V_U_vld_out,
        ack_out => strm_out_TREADY,
        apdone_blk => regslice_both_strm_out_V_last_V_U_apdone_blk);

    regslice_both_strm_out_V_id_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TID,
        vld_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID,
        ack_in => regslice_both_strm_out_V_id_V_U_ack_in_dummy,
        data_out => strm_out_TID,
        vld_out => regslice_both_strm_out_V_id_V_U_vld_out,
        ack_out => strm_out_TREADY,
        apdone_blk => regslice_both_strm_out_V_id_V_U_apdone_blk);

    regslice_both_strm_out_V_dest_V_U : component path_thr_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TDEST,
        vld_in => grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID,
        ack_in => regslice_both_strm_out_V_dest_V_U_ack_in_dummy,
        data_out => strm_out_TDEST,
        vld_out => regslice_both_strm_out_V_dest_V_U_vld_out,
        ack_out => strm_out_TREADY,
        apdone_blk => regslice_both_strm_out_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_ready = ap_const_logic_1)) then 
                    grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = addr_flag_0_loc_load_load_fu_124_p1) and (regslice_both_strm_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                addr <= addr_loc_0_loc_fu_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_flag_0_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                addr_flag_0_loc_fu_78 <= grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_flag_0_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_loc_0_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                addr_loc_0_loc_fu_74 <= grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_addr_loc_0_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_done, ap_CS_fsm, ap_CS_fsm_state3, ap_CS_fsm_state4, regslice_both_strm_out_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_strm_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    addr_flag_0_loc_load_load_fu_124_p1 <= addr_flag_0_loc_fu_78;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_done)
    begin
        if ((grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(regslice_both_strm_out_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_strm_out_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_start <= grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_ap_start_reg;
    grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TREADY <= (strm_out_TREADY_int_regslice and ap_CS_fsm_state3);
    strm_in_TREADY <= regslice_both_strm_in_V_data_V_U_ack_in;

    strm_in_TREADY_int_regslice_assign_proc : process(grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_in_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            strm_in_TREADY_int_regslice <= grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_in_TREADY;
        else 
            strm_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    strm_out_TVALID <= regslice_both_strm_out_V_data_V_U_vld_out;
    strm_out_TVALID_int_regslice <= grp_path_thr_axis_Pipeline_VITIS_LOOP_31_1_fu_82_strm_out_TVALID;
end behav;
