#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("strm_in_TDATA", 64, hls_in, 0, "axis", "in_data", 1),
	Port_Property("strm_in_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("strm_in_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("strm_in_TKEEP", 8, hls_in, 1, "axis", "in_data", 1),
	Port_Property("strm_in_TSTRB", 8, hls_in, 2, "axis", "in_data", 1),
	Port_Property("strm_in_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("strm_in_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("strm_in_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("strm_in_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("received", 1, hls_out, 8, "ap_none", "out_data", 1),
	Port_Property("s_axi_Axi_lite_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_AWADDR", 7, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_ARADDR", 7, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Axi_lite_BRESP", 2, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "colector_display";
